/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *scrolledwindow1n;
  GtkWidget *treeview1n;
  GtkWidget *button1n;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label4;
  GtkWidget *button2n;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label5;
  GtkWidget *vol;
  GtkWidget *fixed3;
  GtkWidget *scrolledwindow2n;
  GtkWidget *treeview2n;
  GtkWidget *button3n;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label6;
  GtkWidget *button4n;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label7;
  GtkWidget *hotel;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("agent"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 936, 544);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  scrolledwindow1n = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1n);
  gtk_fixed_put (GTK_FIXED (fixed2), scrolledwindow1n, 100, 50);
  gtk_widget_set_size_request (scrolledwindow1n, 755, 382);

  treeview1n = gtk_tree_view_new ();
  gtk_widget_show (treeview1n);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1n), treeview1n);

  button1n = gtk_button_new ();
  gtk_widget_show (button1n);
  gtk_fixed_put (GTK_FIXED (fixed2), button1n, 288, 8);
  gtk_widget_set_size_request (button1n, 272, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1n), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox1), label4, FALSE, FALSE, 0);

  button2n = gtk_button_new ();
  gtk_widget_show (button2n);
  gtk_fixed_put (GTK_FIXED (fixed2), button2n, 304, 448);
  gtk_widget_set_size_request (button2n, 272, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2n), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  vol = gtk_label_new (_("vol"));
  gtk_widget_show (vol);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), vol);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  scrolledwindow2n = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2n);
  gtk_fixed_put (GTK_FIXED (fixed3), scrolledwindow2n, 130, 80);
  gtk_widget_set_size_request (scrolledwindow2n, 700, 364);

  treeview2n = gtk_tree_view_new ();
  gtk_widget_show (treeview2n);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2n), treeview2n);

  button3n = gtk_button_new ();
  gtk_widget_show (button3n);
  gtk_fixed_put (GTK_FIXED (fixed3), button3n, 280, 24);
  gtk_widget_set_size_request (button3n, 336, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3n), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  button4n = gtk_button_new ();
  gtk_widget_show (button4n);
  gtk_fixed_put (GTK_FIXED (fixed3), button4n, 368, 464);
  gtk_widget_set_size_request (button4n, 296, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4n), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox4), label7, FALSE, FALSE, 0);

  hotel = gtk_label_new (_("hotel"));
  gtk_widget_show (hotel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), hotel);

  g_signal_connect ((gpointer) treeview1n, "row_activated",
                    G_CALLBACK (on_treeview1n_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button1n, "clicked",
                    G_CALLBACK (on_button1n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2n, "clicked",
                    G_CALLBACK (on_button2n_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview2n, "row_activated",
                    G_CALLBACK (on_treeview2n_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button3n, "clicked",
                    G_CALLBACK (on_button3n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4n, "clicked",
                    G_CALLBACK (on_button4n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1n, "scrolledwindow1n");
  GLADE_HOOKUP_OBJECT (window1, treeview1n, "treeview1n");
  GLADE_HOOKUP_OBJECT (window1, button1n, "button1n");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, button2n, "button2n");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, vol, "vol");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow2n, "scrolledwindow2n");
  GLADE_HOOKUP_OBJECT (window1, treeview2n, "treeview2n");
  GLADE_HOOKUP_OBJECT (window1, button3n, "button3n");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, button4n, "button4n");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, hotel, "hotel");

  return window1;
}

GtkWidget*
create_ajouhotel (void)
{
  GtkWidget *ajouhotel;
  GtkWidget *fixed7;
  GtkWidget *entry1nn;
  GtkWidget *entry2nn;
  GtkWidget *entry3nn;
  GtkObject *spinbutton1nn_adj;
  GtkWidget *spinbutton1nn;
  GtkObject *spinbutton2nn_adj;
  GtkWidget *spinbutton2nn;
  GtkWidget *entry4nn;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *comboboxentry1nn;
  GtkWidget *button12nn;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label35;
  GtkWidget *button13nn;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label36;

  ajouhotel = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouhotel), _("ajouthotel"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (ajouhotel), fixed7);

  entry1nn = gtk_entry_new ();
  gtk_widget_show (entry1nn);
  gtk_fixed_put (GTK_FIXED (fixed7), entry1nn, 224, 40);
  gtk_widget_set_size_request (entry1nn, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1nn), 8226);

  entry2nn = gtk_entry_new ();
  gtk_widget_show (entry2nn);
  gtk_fixed_put (GTK_FIXED (fixed7), entry2nn, 224, 88);
  gtk_widget_set_size_request (entry2nn, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2nn), 8226);

  entry3nn = gtk_entry_new ();
  gtk_widget_show (entry3nn);
  gtk_fixed_put (GTK_FIXED (fixed7), entry3nn, 224, 136);
  gtk_widget_set_size_request (entry3nn, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3nn), 8226);

  spinbutton1nn_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1nn = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1nn_adj), 1, 0);
  gtk_widget_show (spinbutton1nn);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton1nn, 224, 184);
  gtk_widget_set_size_request (spinbutton1nn, 190, 27);

  spinbutton2nn_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2nn = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2nn_adj), 1, 0);
  gtk_widget_show (spinbutton2nn);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton2nn, 224, 328);
  gtk_widget_set_size_request (spinbutton2nn, 190, 27);

  entry4nn = gtk_entry_new ();
  gtk_widget_show (entry4nn);
  gtk_fixed_put (GTK_FIXED (fixed7), entry4nn, 224, 280);
  gtk_widget_set_size_request (entry4nn, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4nn), 8226);

  label27 = gtk_label_new (_("id:"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed7), label27, 16, 48);
  gtk_widget_set_size_request (label27, 24, 17);

  label28 = gtk_label_new (_("localisation:"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed7), label28, 16, 96);
  gtk_widget_set_size_request (label28, 88, 17);

  label29 = gtk_label_new (_("nom:"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed7), label29, 16, 144);
  gtk_widget_set_size_request (label29, 40, 17);

  label30 = gtk_label_new (_("etoiles:"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed7), label30, 16, 192);
  gtk_widget_set_size_request (label30, 56, 17);

  label31 = gtk_label_new (_("type de chambre:"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed7), label31, 16, 240);
  gtk_widget_set_size_request (label31, 116, 17);

  label32 = gtk_label_new (_("prix:"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed7), label32, 16, 288);
  gtk_widget_set_size_request (label32, 30, 17);

  label33 = gtk_label_new (_("nbre de places disponibles:"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed7), label33, 16, 336);
  gtk_widget_set_size_request (label33, 189, 17);

  comboboxentry1nn = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1nn);
  gtk_fixed_put (GTK_FIXED (fixed7), comboboxentry1nn, 224, 232);
  gtk_widget_set_size_request (comboboxentry1nn, 190, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1nn), _("single"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1nn), _("double"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1nn), _("triple"));

  button12nn = gtk_button_new ();
  gtk_widget_show (button12nn);
  gtk_fixed_put (GTK_FIXED (fixed7), button12nn, 296, 408);
  gtk_widget_set_size_request (button12nn, 90, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button12nn), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox12), label35, FALSE, FALSE, 0);

  button13nn = gtk_button_new ();
  gtk_widget_show (button13nn);
  gtk_fixed_put (GTK_FIXED (fixed7), button13nn, 40, 408);
  gtk_widget_set_size_request (button13nn, 90, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button13nn), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox13), label36, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button12nn, "clicked",
                    G_CALLBACK (on_button12nn_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13nn, "clicked",
                    G_CALLBACK (on_button13nn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouhotel, ajouhotel, "ajouhotel");
  GLADE_HOOKUP_OBJECT (ajouhotel, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (ajouhotel, entry1nn, "entry1nn");
  GLADE_HOOKUP_OBJECT (ajouhotel, entry2nn, "entry2nn");
  GLADE_HOOKUP_OBJECT (ajouhotel, entry3nn, "entry3nn");
  GLADE_HOOKUP_OBJECT (ajouhotel, spinbutton1nn, "spinbutton1nn");
  GLADE_HOOKUP_OBJECT (ajouhotel, spinbutton2nn, "spinbutton2nn");
  GLADE_HOOKUP_OBJECT (ajouhotel, entry4nn, "entry4nn");
  GLADE_HOOKUP_OBJECT (ajouhotel, label27, "label27");
  GLADE_HOOKUP_OBJECT (ajouhotel, label28, "label28");
  GLADE_HOOKUP_OBJECT (ajouhotel, label29, "label29");
  GLADE_HOOKUP_OBJECT (ajouhotel, label30, "label30");
  GLADE_HOOKUP_OBJECT (ajouhotel, label31, "label31");
  GLADE_HOOKUP_OBJECT (ajouhotel, label32, "label32");
  GLADE_HOOKUP_OBJECT (ajouhotel, label33, "label33");
  GLADE_HOOKUP_OBJECT (ajouhotel, comboboxentry1nn, "comboboxentry1nn");
  GLADE_HOOKUP_OBJECT (ajouhotel, button12nn, "button12nn");
  GLADE_HOOKUP_OBJECT (ajouhotel, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (ajouhotel, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (ajouhotel, image12, "image12");
  GLADE_HOOKUP_OBJECT (ajouhotel, label35, "label35");
  GLADE_HOOKUP_OBJECT (ajouhotel, button13nn, "button13nn");
  GLADE_HOOKUP_OBJECT (ajouhotel, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (ajouhotel, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (ajouhotel, image13, "image13");
  GLADE_HOOKUP_OBJECT (ajouhotel, label36, "label36");

  return ajouhotel;
}

GtkWidget*
create_modifhotel (void)
{
  GtkWidget *modifhotel;
  GtkWidget *fixed8;
  GtkWidget *entry100n;
  GtkWidget *entry200n;
  GtkWidget *entry300n;
  GtkWidget *entry400n;
  GtkObject *spinbutton100n_adj;
  GtkWidget *spinbutton100n;
  GtkObject *spinbutton200n_adj;
  GtkWidget *spinbutton200n;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label43;
  GtkWidget *label41;
  GtkWidget *label40;
  GtkWidget *label42;
  GtkWidget *button100n;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label44;
  GtkWidget *button102n;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label45;
  GtkWidget *button101n;
  GtkWidget *comboboxentry100n;

  modifhotel = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifhotel), _("modifhotel"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (modifhotel), fixed8);

  entry100n = gtk_entry_new ();
  gtk_widget_show (entry100n);
  gtk_fixed_put (GTK_FIXED (fixed8), entry100n, 224, 40);
  gtk_widget_set_size_request (entry100n, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry100n), 8226);

  entry200n = gtk_entry_new ();
  gtk_widget_show (entry200n);
  gtk_fixed_put (GTK_FIXED (fixed8), entry200n, 224, 88);
  gtk_widget_set_size_request (entry200n, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry200n), 8226);

  entry300n = gtk_entry_new ();
  gtk_widget_show (entry300n);
  gtk_fixed_put (GTK_FIXED (fixed8), entry300n, 224, 136);
  gtk_widget_set_size_request (entry300n, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry300n), 8226);

  entry400n = gtk_entry_new ();
  gtk_widget_show (entry400n);
  gtk_fixed_put (GTK_FIXED (fixed8), entry400n, 224, 280);
  gtk_widget_set_size_request (entry400n, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry400n), 8226);

  spinbutton100n_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton100n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton100n_adj), 1, 0);
  gtk_widget_show (spinbutton100n);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton100n, 224, 184);
  gtk_widget_set_size_request (spinbutton100n, 190, 27);

  spinbutton200n_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton200n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton200n_adj), 1, 0);
  gtk_widget_show (spinbutton200n);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton200n, 224, 328);
  gtk_widget_set_size_request (spinbutton200n, 190, 27);

  label37 = gtk_label_new (_("id:"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed8), label37, 16, 48);
  gtk_widget_set_size_request (label37, 24, 17);

  label38 = gtk_label_new (_("localisation:"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed8), label38, 16, 96);
  gtk_widget_set_size_request (label38, 88, 17);

  label39 = gtk_label_new (_("nom:"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed8), label39, 16, 144);
  gtk_widget_set_size_request (label39, 40, 17);

  label43 = gtk_label_new (_("etoiles:"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed8), label43, 16, 192);
  gtk_widget_set_size_request (label43, 56, 17);

  label41 = gtk_label_new (_("prix:"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed8), label41, 16, 288);
  gtk_widget_set_size_request (label41, 30, 17);

  label40 = gtk_label_new (_("type de chambre:"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed8), label40, 16, 240);
  gtk_widget_set_size_request (label40, 116, 17);

  label42 = gtk_label_new (_("nbre de places disponibles:"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed8), label42, 16, 336);
  gtk_widget_set_size_request (label42, 189, 17);

  button100n = gtk_button_new ();
  gtk_widget_show (button100n);
  gtk_fixed_put (GTK_FIXED (fixed8), button100n, 40, 408);
  gtk_widget_set_size_request (button100n, 90, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button100n), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox14), label44, FALSE, FALSE, 0);

  button102n = gtk_button_new ();
  gtk_widget_show (button102n);
  gtk_fixed_put (GTK_FIXED (fixed8), button102n, 296, 408);
  gtk_widget_set_size_request (button102n, 90, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button102n), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox15), label45, FALSE, FALSE, 0);

  button101n = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (button101n);
  gtk_fixed_put (GTK_FIXED (fixed8), button101n, 168, 408);
  gtk_widget_set_size_request (button101n, 90, 29);

  comboboxentry100n = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry100n);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentry100n, 224, 232);
  gtk_widget_set_size_request (comboboxentry100n, 190, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry100n), _("simple "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry100n), _("double"));

  g_signal_connect ((gpointer) button100n, "clicked",
                    G_CALLBACK (on_button100n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button102n, "clicked",
                    G_CALLBACK (on_button102n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button101n, "clicked",
                    G_CALLBACK (on_button101n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifhotel, modifhotel, "modifhotel");
  GLADE_HOOKUP_OBJECT (modifhotel, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (modifhotel, entry100n, "entry100n");
  GLADE_HOOKUP_OBJECT (modifhotel, entry200n, "entry200n");
  GLADE_HOOKUP_OBJECT (modifhotel, entry300n, "entry300n");
  GLADE_HOOKUP_OBJECT (modifhotel, entry400n, "entry400n");
  GLADE_HOOKUP_OBJECT (modifhotel, spinbutton100n, "spinbutton100n");
  GLADE_HOOKUP_OBJECT (modifhotel, spinbutton200n, "spinbutton200n");
  GLADE_HOOKUP_OBJECT (modifhotel, label37, "label37");
  GLADE_HOOKUP_OBJECT (modifhotel, label38, "label38");
  GLADE_HOOKUP_OBJECT (modifhotel, label39, "label39");
  GLADE_HOOKUP_OBJECT (modifhotel, label43, "label43");
  GLADE_HOOKUP_OBJECT (modifhotel, label41, "label41");
  GLADE_HOOKUP_OBJECT (modifhotel, label40, "label40");
  GLADE_HOOKUP_OBJECT (modifhotel, label42, "label42");
  GLADE_HOOKUP_OBJECT (modifhotel, button100n, "button100n");
  GLADE_HOOKUP_OBJECT (modifhotel, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (modifhotel, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (modifhotel, image14, "image14");
  GLADE_HOOKUP_OBJECT (modifhotel, label44, "label44");
  GLADE_HOOKUP_OBJECT (modifhotel, button102n, "button102n");
  GLADE_HOOKUP_OBJECT (modifhotel, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (modifhotel, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (modifhotel, image15, "image15");
  GLADE_HOOKUP_OBJECT (modifhotel, label45, "label45");
  GLADE_HOOKUP_OBJECT (modifhotel, button101n, "button101n");
  GLADE_HOOKUP_OBJECT (modifhotel, comboboxentry100n, "comboboxentry100n");

  return modifhotel;
}

GtkWidget*
create_ajouvol (void)
{
  GtkWidget *ajouvol;
  GtkWidget *fixed9;
  GtkWidget *entry01n;
  GtkWidget *entry02n;
  GtkWidget *entry03n;
  GtkObject *spinbutton01n_adj;
  GtkWidget *spinbutton01n;
  GtkObject *spinbutton02n_adj;
  GtkWidget *spinbutton02n;
  GtkObject *spinbutton03n_adj;
  GtkWidget *spinbutton03n;
  GtkWidget *entry04n;
  GtkWidget *entry05n;
  GtkObject *spinbutton04n_adj;
  GtkWidget *spinbutton04n;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *comboboxentry01n;
  GtkWidget *label49;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *label53;
  GtkWidget *label52;
  GtkWidget *button01n;

  ajouvol = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouvol), _("ajouvol"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (ajouvol), fixed9);

  entry01n = gtk_entry_new ();
  gtk_widget_show (entry01n);
  gtk_fixed_put (GTK_FIXED (fixed9), entry01n, 200, 24);
  gtk_widget_set_size_request (entry01n, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry01n), 8226);

  entry02n = gtk_entry_new ();
  gtk_widget_show (entry02n);
  gtk_fixed_put (GTK_FIXED (fixed9), entry02n, 200, 72);
  gtk_widget_set_size_request (entry02n, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry02n), 8226);

  entry03n = gtk_entry_new ();
  gtk_widget_show (entry03n);
  gtk_fixed_put (GTK_FIXED (fixed9), entry03n, 200, 120);
  gtk_widget_set_size_request (entry03n, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry03n), 8226);

  spinbutton01n_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton01n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton01n_adj), 1, 0);
  gtk_widget_show (spinbutton01n);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton01n, 200, 168);
  gtk_widget_set_size_request (spinbutton01n, 60, 27);

  spinbutton02n_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton02n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton02n_adj), 1, 0);
  gtk_widget_show (spinbutton02n);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton02n, 264, 168);
  gtk_widget_set_size_request (spinbutton02n, 60, 27);

  spinbutton03n_adj = gtk_adjustment_new (1, 1900, 2200, 1, 10, 10);
  spinbutton03n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton03n_adj), 1, 0);
  gtk_widget_show (spinbutton03n);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton03n, 328, 168);
  gtk_widget_set_size_request (spinbutton03n, 60, 27);

  entry04n = gtk_entry_new ();
  gtk_widget_show (entry04n);
  gtk_fixed_put (GTK_FIXED (fixed9), entry04n, 200, 216);
  gtk_widget_set_size_request (entry04n, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry04n), 8226);

  entry05n = gtk_entry_new ();
  gtk_widget_show (entry05n);
  gtk_fixed_put (GTK_FIXED (fixed9), entry05n, 200, 312);
  gtk_widget_set_size_request (entry05n, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry05n), 8226);

  spinbutton04n_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton04n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton04n_adj), 1, 0);
  gtk_widget_show (spinbutton04n);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton04n, 200, 360);
  gtk_widget_set_size_request (spinbutton04n, 190, 27);

  label46 = gtk_label_new (_("id:"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed9), label46, 16, 32);
  gtk_widget_set_size_request (label46, 24, 17);

  label47 = gtk_label_new (_("heure depart :"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed9), label47, 16, 80);
  gtk_widget_set_size_request (label47, 96, 17);

  label48 = gtk_label_new (_("heure arriv\303\251:"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed9), label48, 16, 128);
  gtk_widget_set_size_request (label48, 88, 17);

  comboboxentry01n = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry01n);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry01n, 200, 264);
  gtk_widget_set_size_request (comboboxentry01n, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry01n), _("allez-simple"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry01n), _("allez-retour"));

  label49 = gtk_label_new (_("date:"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed9), label49, 16, 176);
  gtk_widget_set_size_request (label49, 35, 17);

  label50 = gtk_label_new (_("dur\303\251e du vol:"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed9), label50, 16, 224);
  gtk_widget_set_size_request (label50, 90, 17);

  label51 = gtk_label_new (_("type:"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed9), label51, 16, 272);
  gtk_widget_set_size_request (label51, 35, 17);

  label53 = gtk_label_new (_("prix:"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed9), label53, 16, 320);
  gtk_widget_set_size_request (label53, 35, 17);

  label52 = gtk_label_new (_("nbre de places:"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed9), label52, 16, 368);
  gtk_widget_set_size_request (label52, 101, 17);

  button01n = gtk_button_new_with_mnemonic (_("valider"));
  gtk_widget_show (button01n);
  gtk_fixed_put (GTK_FIXED (fixed9), button01n, 128, 408);
  gtk_widget_set_size_request (button01n, 90, 29);

  g_signal_connect ((gpointer) button01n, "clicked",
                    G_CALLBACK (on_button01n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouvol, ajouvol, "ajouvol");
  GLADE_HOOKUP_OBJECT (ajouvol, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (ajouvol, entry01n, "entry01n");
  GLADE_HOOKUP_OBJECT (ajouvol, entry02n, "entry02n");
  GLADE_HOOKUP_OBJECT (ajouvol, entry03n, "entry03n");
  GLADE_HOOKUP_OBJECT (ajouvol, spinbutton01n, "spinbutton01n");
  GLADE_HOOKUP_OBJECT (ajouvol, spinbutton02n, "spinbutton02n");
  GLADE_HOOKUP_OBJECT (ajouvol, spinbutton03n, "spinbutton03n");
  GLADE_HOOKUP_OBJECT (ajouvol, entry04n, "entry04n");
  GLADE_HOOKUP_OBJECT (ajouvol, entry05n, "entry05n");
  GLADE_HOOKUP_OBJECT (ajouvol, spinbutton04n, "spinbutton04n");
  GLADE_HOOKUP_OBJECT (ajouvol, label46, "label46");
  GLADE_HOOKUP_OBJECT (ajouvol, label47, "label47");
  GLADE_HOOKUP_OBJECT (ajouvol, label48, "label48");
  GLADE_HOOKUP_OBJECT (ajouvol, comboboxentry01n, "comboboxentry01n");
  GLADE_HOOKUP_OBJECT (ajouvol, label49, "label49");
  GLADE_HOOKUP_OBJECT (ajouvol, label50, "label50");
  GLADE_HOOKUP_OBJECT (ajouvol, label51, "label51");
  GLADE_HOOKUP_OBJECT (ajouvol, label53, "label53");
  GLADE_HOOKUP_OBJECT (ajouvol, label52, "label52");
  GLADE_HOOKUP_OBJECT (ajouvol, button01n, "button01n");

  return ajouvol;
}

GtkWidget*
create_modifvol (void)
{
  GtkWidget *modifvol;
  GtkWidget *fixed10;
  GtkWidget *entrykh1;
  GtkWidget *entrykh2;
  GtkWidget *entrykh3;
  GtkWidget *entrykh4;
  GtkWidget *entrykh5;
  GtkObject *spinbuttonkh1_adj;
  GtkWidget *spinbuttonkh1;
  GtkObject *spinbuttonkh2_adj;
  GtkWidget *spinbuttonkh2;
  GtkObject *spinbuttonkh3_adj;
  GtkWidget *spinbuttonkh3;
  GtkObject *spinbuttonkh4_adj;
  GtkWidget *spinbuttonkh4;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *buttonkh1;
  GtkWidget *buttonkh2;
  GtkWidget *buttonkh3;
  GtkWidget *comboboxentrykh1;

  modifvol = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifvol), _("modifvol"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (modifvol), fixed10);

  entrykh1 = gtk_entry_new ();
  gtk_widget_show (entrykh1);
  gtk_fixed_put (GTK_FIXED (fixed10), entrykh1, 200, 24);
  gtk_widget_set_size_request (entrykh1, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrykh1), 8226);

  entrykh2 = gtk_entry_new ();
  gtk_widget_show (entrykh2);
  gtk_fixed_put (GTK_FIXED (fixed10), entrykh2, 200, 72);
  gtk_widget_set_size_request (entrykh2, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrykh2), 8226);

  entrykh3 = gtk_entry_new ();
  gtk_widget_show (entrykh3);
  gtk_fixed_put (GTK_FIXED (fixed10), entrykh3, 200, 120);
  gtk_widget_set_size_request (entrykh3, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrykh3), 8226);

  entrykh4 = gtk_entry_new ();
  gtk_widget_show (entrykh4);
  gtk_fixed_put (GTK_FIXED (fixed10), entrykh4, 200, 216);
  gtk_widget_set_size_request (entrykh4, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrykh4), 8226);

  entrykh5 = gtk_entry_new ();
  gtk_widget_show (entrykh5);
  gtk_fixed_put (GTK_FIXED (fixed10), entrykh5, 200, 312);
  gtk_widget_set_size_request (entrykh5, 190, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrykh5), 8226);

  spinbuttonkh1_adj = gtk_adjustment_new (1, 1, 23, 1, 10, 10);
  spinbuttonkh1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonkh1_adj), 1, 0);
  gtk_widget_show (spinbuttonkh1);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbuttonkh1, 200, 168);
  gtk_widget_set_size_request (spinbuttonkh1, 60, 27);

  spinbuttonkh2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonkh2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonkh2_adj), 1, 0);
  gtk_widget_show (spinbuttonkh2);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbuttonkh2, 264, 168);
  gtk_widget_set_size_request (spinbuttonkh2, 60, 27);

  spinbuttonkh3_adj = gtk_adjustment_new (1, 1900, 2200, 1, 10, 10);
  spinbuttonkh3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonkh3_adj), 1, 0);
  gtk_widget_show (spinbuttonkh3);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbuttonkh3, 328, 168);
  gtk_widget_set_size_request (spinbuttonkh3, 60, 27);

  spinbuttonkh4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonkh4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonkh4_adj), 1, 0);
  gtk_widget_show (spinbuttonkh4);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbuttonkh4, 200, 360);
  gtk_widget_set_size_request (spinbuttonkh4, 190, 27);

  label54 = gtk_label_new (_("id:"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed10), label54, 16, 32);
  gtk_widget_set_size_request (label54, 24, 17);

  label55 = gtk_label_new (_("heure depart:"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed10), label55, 16, 80);
  gtk_widget_set_size_request (label55, 96, 17);

  label56 = gtk_label_new (_("heure arriv\303\251:"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed10), label56, 16, 128);
  gtk_widget_set_size_request (label56, 88, 17);

  label57 = gtk_label_new (_("date:"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed10), label57, 16, 176);
  gtk_widget_set_size_request (label57, 35, 17);

  label58 = gtk_label_new (_("dur\303\251e du vol:"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed10), label58, 16, 224);
  gtk_widget_set_size_request (label58, 90, 17);

  label59 = gtk_label_new (_("type:"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed10), label59, 16, 272);
  gtk_widget_set_size_request (label59, 35, 17);

  label60 = gtk_label_new (_("prix:"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed10), label60, 16, 320);
  gtk_widget_set_size_request (label60, 35, 17);

  label61 = gtk_label_new (_("nbre des places:"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed10), label61, 16, 368);
  gtk_widget_set_size_request (label61, 101, 17);

  buttonkh1 = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (buttonkh1);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonkh1, 32, 408);
  gtk_widget_set_size_request (buttonkh1, 90, 29);

  buttonkh2 = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (buttonkh2);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonkh2, 152, 408);
  gtk_widget_set_size_request (buttonkh2, 90, 29);

  buttonkh3 = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (buttonkh3);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonkh3, 272, 408);
  gtk_widget_set_size_request (buttonkh3, 90, 29);

  comboboxentrykh1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrykh1);
  gtk_fixed_put (GTK_FIXED (fixed10), comboboxentrykh1, 200, 264);
  gtk_widget_set_size_request (comboboxentrykh1, 190, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrykh1), _("aller-simple"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrykh1), _("aller-retour"));

  g_signal_connect ((gpointer) buttonkh1, "clicked",
                    G_CALLBACK (on_buttonkh1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonkh2, "clicked",
                    G_CALLBACK (on_buttonkh2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonkh3, "clicked",
                    G_CALLBACK (on_buttonkh3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifvol, modifvol, "modifvol");
  GLADE_HOOKUP_OBJECT (modifvol, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (modifvol, entrykh1, "entrykh1");
  GLADE_HOOKUP_OBJECT (modifvol, entrykh2, "entrykh2");
  GLADE_HOOKUP_OBJECT (modifvol, entrykh3, "entrykh3");
  GLADE_HOOKUP_OBJECT (modifvol, entrykh4, "entrykh4");
  GLADE_HOOKUP_OBJECT (modifvol, entrykh5, "entrykh5");
  GLADE_HOOKUP_OBJECT (modifvol, spinbuttonkh1, "spinbuttonkh1");
  GLADE_HOOKUP_OBJECT (modifvol, spinbuttonkh2, "spinbuttonkh2");
  GLADE_HOOKUP_OBJECT (modifvol, spinbuttonkh3, "spinbuttonkh3");
  GLADE_HOOKUP_OBJECT (modifvol, spinbuttonkh4, "spinbuttonkh4");
  GLADE_HOOKUP_OBJECT (modifvol, label54, "label54");
  GLADE_HOOKUP_OBJECT (modifvol, label55, "label55");
  GLADE_HOOKUP_OBJECT (modifvol, label56, "label56");
  GLADE_HOOKUP_OBJECT (modifvol, label57, "label57");
  GLADE_HOOKUP_OBJECT (modifvol, label58, "label58");
  GLADE_HOOKUP_OBJECT (modifvol, label59, "label59");
  GLADE_HOOKUP_OBJECT (modifvol, label60, "label60");
  GLADE_HOOKUP_OBJECT (modifvol, label61, "label61");
  GLADE_HOOKUP_OBJECT (modifvol, buttonkh1, "buttonkh1");
  GLADE_HOOKUP_OBJECT (modifvol, buttonkh2, "buttonkh2");
  GLADE_HOOKUP_OBJECT (modifvol, buttonkh3, "buttonkh3");
  GLADE_HOOKUP_OBJECT (modifvol, comboboxentrykh1, "comboboxentrykh1");

  return modifvol;
}

GtkWidget*
create_window3s (void)
{
  GtkWidget *window3s;
  GtkWidget *fixed11;
  GtkWidget *label30s;
  GtkWidget *treeview1;
  GtkWidget *modif_agent;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label65;
  GtkWidget *ajout_agent;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label64;
  GtkWidget *Afficher_agent;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label63;

  window3s = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3s), _("Administrateur"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (window3s), fixed11);

  label30s = gtk_label_new (_("List des Agents"));
  gtk_widget_show (label30s);
  gtk_fixed_put (GTK_FIXED (fixed11), label30s, 280, 8);
  gtk_widget_set_size_request (label30s, 144, 32);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed11), treeview1, 8, 56);
  gtk_widget_set_size_request (treeview1, 640, 392);

  modif_agent = gtk_button_new ();
  gtk_widget_show (modif_agent);
  gtk_fixed_put (GTK_FIXED (fixed11), modif_agent, 832, 408);
  gtk_widget_set_size_request (modif_agent, 104, 37);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (modif_agent), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label65 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label65);
  gtk_box_pack_start (GTK_BOX (hbox18), label65, FALSE, FALSE, 0);

  ajout_agent = gtk_button_new ();
  gtk_widget_show (ajout_agent);
  gtk_fixed_put (GTK_FIXED (fixed11), ajout_agent, 664, 408);
  gtk_widget_set_size_request (ajout_agent, 104, 37);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (ajout_agent), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label64 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox17), label64, FALSE, FALSE, 0);

  Afficher_agent = gtk_button_new ();
  gtk_widget_show (Afficher_agent);
  gtk_fixed_put (GTK_FIXED (fixed11), Afficher_agent, 736, 56);
  gtk_widget_set_size_request (Afficher_agent, 112, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (Afficher_agent), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-orientation-landscape", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label63 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox16), label63, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) modif_agent, "clicked",
                    G_CALLBACK (on_modif_agent_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout_agent, "clicked",
                    G_CALLBACK (on_ajout_agent_clicked),
                    NULL);
  g_signal_connect ((gpointer) Afficher_agent, "clicked",
                    G_CALLBACK (on_Afficher_agent_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3s, window3s, "window3s");
  GLADE_HOOKUP_OBJECT (window3s, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window3s, label30s, "label30s");
  GLADE_HOOKUP_OBJECT (window3s, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window3s, modif_agent, "modif_agent");
  GLADE_HOOKUP_OBJECT (window3s, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window3s, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window3s, image18, "image18");
  GLADE_HOOKUP_OBJECT (window3s, label65, "label65");
  GLADE_HOOKUP_OBJECT (window3s, ajout_agent, "ajout_agent");
  GLADE_HOOKUP_OBJECT (window3s, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window3s, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window3s, image17, "image17");
  GLADE_HOOKUP_OBJECT (window3s, label64, "label64");
  GLADE_HOOKUP_OBJECT (window3s, Afficher_agent, "Afficher_agent");
  GLADE_HOOKUP_OBJECT (window3s, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window3s, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window3s, image16, "image16");
  GLADE_HOOKUP_OBJECT (window3s, label63, "label63");

  return window3s;
}

GtkWidget*
create_window4s (void)
{
  GtkWidget *window4s;
  GtkWidget *fixed12;
  GtkWidget *entry13s;
  GtkWidget *entry14s;
  GtkWidget *entry3s;
  GtkWidget *entry4s;
  GtkWidget *entry17s;
  GtkWidget *entry6s;
  GtkWidget *entry5s;
  GtkWidget *entry7s;
  GtkObject *spinbutton1s_adj;
  GtkWidget *spinbutton1s;
  GtkObject *spinbutton2s_adj;
  GtkWidget *spinbutton2s;
  GtkObject *spinbutton3s_adj;
  GtkWidget *spinbutton3s;
  GtkWidget *labelids;
  GtkWidget *labelpasswords;
  GtkWidget *nom_clients;
  GtkWidget *Prenom_clients;
  GtkWidget *type_de__clientsvoyage;
  GtkWidget *date_de_clients;
  GtkWidget *adresse_clients;
  GtkWidget *e_mail_clients;
  GtkWidget *num_tel_clients;
  GtkWidget *label31s;
  GtkWidget *combobox1s;
  GtkWidget *label33s;
  GtkWidget *button_return;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label77;
  GtkWidget *confirmer;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label78;

  window4s = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4s), _("Ajout agent"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (window4s), fixed12);

  entry13s = gtk_entry_new ();
  gtk_widget_show (entry13s);
  gtk_fixed_put (GTK_FIXED (fixed12), entry13s, 128, 24);
  gtk_widget_set_size_request (entry13s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13s), 8226);

  entry14s = gtk_entry_new ();
  gtk_widget_show (entry14s);
  gtk_fixed_put (GTK_FIXED (fixed12), entry14s, 128, 72);
  gtk_widget_set_size_request (entry14s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14s), 8226);

  entry3s = gtk_entry_new ();
  gtk_widget_show (entry3s);
  gtk_fixed_put (GTK_FIXED (fixed12), entry3s, 128, 120);
  gtk_widget_set_size_request (entry3s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3s), 8226);

  entry4s = gtk_entry_new ();
  gtk_widget_show (entry4s);
  gtk_fixed_put (GTK_FIXED (fixed12), entry4s, 128, 168);
  gtk_widget_set_size_request (entry4s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4s), 8226);

  entry17s = gtk_entry_new ();
  gtk_widget_show (entry17s);
  gtk_fixed_put (GTK_FIXED (fixed12), entry17s, 128, 456);
  gtk_widget_set_size_request (entry17s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17s), 8226);

  entry6s = gtk_entry_new ();
  gtk_widget_show (entry6s);
  gtk_fixed_put (GTK_FIXED (fixed12), entry6s, 128, 408);
  gtk_widget_set_size_request (entry6s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6s), 8226);

  entry5s = gtk_entry_new ();
  gtk_widget_show (entry5s);
  gtk_fixed_put (GTK_FIXED (fixed12), entry5s, 128, 360);
  gtk_widget_set_size_request (entry5s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5s), 8226);

  entry7s = gtk_entry_new ();
  gtk_widget_show (entry7s);
  gtk_fixed_put (GTK_FIXED (fixed12), entry7s, 128, 312);
  gtk_widget_set_size_request (entry7s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7s), 8226);

  spinbutton1s_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1s = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1s_adj), 1, 0);
  gtk_widget_show (spinbutton1s);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton1s, 160, 264);
  gtk_widget_set_size_request (spinbutton1s, 56, 24);

  spinbutton2s_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2s = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2s_adj), 1, 0);
  gtk_widget_show (spinbutton2s);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton2s, 232, 264);
  gtk_widget_set_size_request (spinbutton2s, 56, 24);

  spinbutton3s_adj = gtk_adjustment_new (1, 1960, 2000, 1, 10, 10);
  spinbutton3s = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3s_adj), 1, 0);
  gtk_widget_show (spinbutton3s);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton3s, 312, 264);
  gtk_widget_set_size_request (spinbutton3s, 56, 24);

  labelids = gtk_label_new (_("ID_agent:"));
  gtk_widget_show (labelids);
  gtk_fixed_put (GTK_FIXED (fixed12), labelids, 24, 24);
  gtk_widget_set_size_request (labelids, 88, 32);

  labelpasswords = gtk_label_new (_("Password:"));
  gtk_widget_show (labelpasswords);
  gtk_fixed_put (GTK_FIXED (fixed12), labelpasswords, 32, 73);
  gtk_widget_set_size_request (labelpasswords, 88, 23);

  nom_clients = gtk_label_new (_("Nom:"));
  gtk_widget_show (nom_clients);
  gtk_fixed_put (GTK_FIXED (fixed12), nom_clients, 32, 120);
  gtk_widget_set_size_request (nom_clients, 80, 24);

  Prenom_clients = gtk_label_new (_("Prenom:"));
  gtk_widget_show (Prenom_clients);
  gtk_fixed_put (GTK_FIXED (fixed12), Prenom_clients, 16, 168);
  gtk_widget_set_size_request (Prenom_clients, 88, 24);

  type_de__clientsvoyage = gtk_label_new (_("Sexe:"));
  gtk_widget_show (type_de__clientsvoyage);
  gtk_fixed_put (GTK_FIXED (fixed12), type_de__clientsvoyage, 32, 216);
  gtk_widget_set_size_request (type_de__clientsvoyage, 49, 17);

  date_de_clients = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (date_de_clients);
  gtk_fixed_put (GTK_FIXED (fixed12), date_de_clients, 8, 264);
  gtk_widget_set_size_request (date_de_clients, 144, 23);

  adresse_clients = gtk_label_new (_("Adresse:"));
  gtk_widget_show (adresse_clients);
  gtk_fixed_put (GTK_FIXED (fixed12), adresse_clients, 24, 312);
  gtk_widget_set_size_request (adresse_clients, 88, 24);

  e_mail_clients = gtk_label_new (_("E-mail:"));
  gtk_widget_show (e_mail_clients);
  gtk_fixed_put (GTK_FIXED (fixed12), e_mail_clients, 24, 360);
  gtk_widget_set_size_request (e_mail_clients, 88, 24);

  num_tel_clients = gtk_label_new (_("Num tel:"));
  gtk_widget_show (num_tel_clients);
  gtk_fixed_put (GTK_FIXED (fixed12), num_tel_clients, 32, 408);
  gtk_widget_set_size_request (num_tel_clients, 72, 24);

  label31s = gtk_label_new (_("Pass:"));
  gtk_widget_show (label31s);
  gtk_fixed_put (GTK_FIXED (fixed12), label31s, 32, 456);
  gtk_widget_set_size_request (label31s, 72, 24);

  combobox1s = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1s);
  gtk_fixed_put (GTK_FIXED (fixed12), combobox1s, 128, 216);
  gtk_widget_set_size_request (combobox1s, 160, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1s), _("FEMME"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1s), _("HOMME"));

  label33s = gtk_label_new ("");
  gtk_widget_show (label33s);
  gtk_fixed_put (GTK_FIXED (fixed12), label33s, 120, 520);
  gtk_widget_set_size_request (label33s, 192, 41);

  button_return = gtk_button_new ();
  gtk_widget_show (button_return);
  gtk_fixed_put (GTK_FIXED (fixed12), button_return, 0, 520);
  gtk_widget_set_size_request (button_return, 96, 40);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button_return), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label77 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox19), label77, FALSE, FALSE, 0);

  confirmer = gtk_button_new ();
  gtk_widget_show (confirmer);
  gtk_fixed_put (GTK_FIXED (fixed12), confirmer, 304, 520);
  gtk_widget_set_size_request (confirmer, 112, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (confirmer), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label78 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (hbox20), label78, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_return, "clicked",
                    G_CALLBACK (on_button_return_clicked),
                    NULL);
  g_signal_connect ((gpointer) confirmer, "clicked",
                    G_CALLBACK (on_confirmer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4s, window4s, "window4s");
  GLADE_HOOKUP_OBJECT (window4s, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window4s, entry13s, "entry13s");
  GLADE_HOOKUP_OBJECT (window4s, entry14s, "entry14s");
  GLADE_HOOKUP_OBJECT (window4s, entry3s, "entry3s");
  GLADE_HOOKUP_OBJECT (window4s, entry4s, "entry4s");
  GLADE_HOOKUP_OBJECT (window4s, entry17s, "entry17s");
  GLADE_HOOKUP_OBJECT (window4s, entry6s, "entry6s");
  GLADE_HOOKUP_OBJECT (window4s, entry5s, "entry5s");
  GLADE_HOOKUP_OBJECT (window4s, entry7s, "entry7s");
  GLADE_HOOKUP_OBJECT (window4s, spinbutton1s, "spinbutton1s");
  GLADE_HOOKUP_OBJECT (window4s, spinbutton2s, "spinbutton2s");
  GLADE_HOOKUP_OBJECT (window4s, spinbutton3s, "spinbutton3s");
  GLADE_HOOKUP_OBJECT (window4s, labelids, "labelids");
  GLADE_HOOKUP_OBJECT (window4s, labelpasswords, "labelpasswords");
  GLADE_HOOKUP_OBJECT (window4s, nom_clients, "nom_clients");
  GLADE_HOOKUP_OBJECT (window4s, Prenom_clients, "Prenom_clients");
  GLADE_HOOKUP_OBJECT (window4s, type_de__clientsvoyage, "type_de__clientsvoyage");
  GLADE_HOOKUP_OBJECT (window4s, date_de_clients, "date_de_clients");
  GLADE_HOOKUP_OBJECT (window4s, adresse_clients, "adresse_clients");
  GLADE_HOOKUP_OBJECT (window4s, e_mail_clients, "e_mail_clients");
  GLADE_HOOKUP_OBJECT (window4s, num_tel_clients, "num_tel_clients");
  GLADE_HOOKUP_OBJECT (window4s, label31s, "label31s");
  GLADE_HOOKUP_OBJECT (window4s, combobox1s, "combobox1s");
  GLADE_HOOKUP_OBJECT (window4s, label33s, "label33s");
  GLADE_HOOKUP_OBJECT (window4s, button_return, "button_return");
  GLADE_HOOKUP_OBJECT (window4s, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window4s, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window4s, image19, "image19");
  GLADE_HOOKUP_OBJECT (window4s, label77, "label77");
  GLADE_HOOKUP_OBJECT (window4s, confirmer, "confirmer");
  GLADE_HOOKUP_OBJECT (window4s, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window4s, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window4s, image20, "image20");
  GLADE_HOOKUP_OBJECT (window4s, label78, "label78");

  return window4s;
}

GtkWidget*
create_window5s (void)
{
  GtkWidget *window5s;
  GtkWidget *fixed13;
  GtkWidget *entry15s;
  GtkWidget *entry16s;
  GtkWidget *entry8s;
  GtkWidget *entry9s;
  GtkObject *spinbutton4s_adj;
  GtkWidget *spinbutton4s;
  GtkObject *spinbutton5s_adj;
  GtkWidget *spinbutton5s;
  GtkObject *spinbutton6s_adj;
  GtkWidget *spinbutton6s;
  GtkWidget *entry11s;
  GtkWidget *entry12s;
  GtkWidget *entry10s;
  GtkWidget *entry18s;
  GtkWidget *labelid2s;
  GtkWidget *labelpassword2s;
  GtkWidget *label16s;
  GtkWidget *label17s;
  GtkWidget *sexes;
  GtkWidget *label19s;
  GtkWidget *label20s;
  GtkWidget *label21s;
  GtkWidget *label18s;
  GtkWidget *label34s;
  GtkWidget *combobox2s;
  GtkWidget *label36s;
  GtkWidget *retour_Administrateur;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label90;
  GtkWidget *supprimer_agent;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label91;
  GtkWidget *confirmer_modif_agent;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label92;

  window5s = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5s), _("Modifier agent"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (window5s), fixed13);

  entry15s = gtk_entry_new ();
  gtk_widget_show (entry15s);
  gtk_fixed_put (GTK_FIXED (fixed13), entry15s, 128, 24);
  gtk_widget_set_size_request (entry15s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15s), 8226);

  entry16s = gtk_entry_new ();
  gtk_widget_show (entry16s);
  gtk_fixed_put (GTK_FIXED (fixed13), entry16s, 128, 72);
  gtk_widget_set_size_request (entry16s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16s), 8226);

  entry8s = gtk_entry_new ();
  gtk_widget_show (entry8s);
  gtk_fixed_put (GTK_FIXED (fixed13), entry8s, 128, 120);
  gtk_widget_set_size_request (entry8s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8s), 8226);

  entry9s = gtk_entry_new ();
  gtk_widget_show (entry9s);
  gtk_fixed_put (GTK_FIXED (fixed13), entry9s, 128, 168);
  gtk_widget_set_size_request (entry9s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9s), 8226);

  spinbutton4s_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton4s = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4s_adj), 1, 0);
  gtk_widget_show (spinbutton4s);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton4s, 160, 264);
  gtk_widget_set_size_request (spinbutton4s, 56, 24);

  spinbutton5s_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton5s = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5s_adj), 1, 0);
  gtk_widget_show (spinbutton5s);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton5s, 232, 264);
  gtk_widget_set_size_request (spinbutton5s, 56, 24);

  spinbutton6s_adj = gtk_adjustment_new (1, 1960, 2000, 1, 10, 10);
  spinbutton6s = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6s_adj), 1, 0);
  gtk_widget_show (spinbutton6s);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton6s, 312, 264);
  gtk_widget_set_size_request (spinbutton6s, 56, 24);

  entry11s = gtk_entry_new ();
  gtk_widget_show (entry11s);
  gtk_fixed_put (GTK_FIXED (fixed13), entry11s, 128, 312);
  gtk_widget_set_size_request (entry11s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11s), 8226);

  entry12s = gtk_entry_new ();
  gtk_widget_show (entry12s);
  gtk_fixed_put (GTK_FIXED (fixed13), entry12s, 128, 360);
  gtk_widget_set_size_request (entry12s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12s), 8226);

  entry10s = gtk_entry_new ();
  gtk_widget_show (entry10s);
  gtk_fixed_put (GTK_FIXED (fixed13), entry10s, 128, 408);
  gtk_widget_set_size_request (entry10s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10s), 8226);

  entry18s = gtk_entry_new ();
  gtk_widget_show (entry18s);
  gtk_fixed_put (GTK_FIXED (fixed13), entry18s, 128, 456);
  gtk_widget_set_size_request (entry18s, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18s), 8226);

  labelid2s = gtk_label_new (_("ID_agent:"));
  gtk_widget_show (labelid2s);
  gtk_fixed_put (GTK_FIXED (fixed13), labelid2s, 24, 24);
  gtk_widget_set_size_request (labelid2s, 88, 32);

  labelpassword2s = gtk_label_new (_("Password:"));
  gtk_widget_show (labelpassword2s);
  gtk_fixed_put (GTK_FIXED (fixed13), labelpassword2s, 32, 73);
  gtk_widget_set_size_request (labelpassword2s, 88, 23);

  label16s = gtk_label_new (_("Nom:"));
  gtk_widget_show (label16s);
  gtk_fixed_put (GTK_FIXED (fixed13), label16s, 32, 120);
  gtk_widget_set_size_request (label16s, 80, 24);

  label17s = gtk_label_new (_("Prenom:"));
  gtk_widget_show (label17s);
  gtk_fixed_put (GTK_FIXED (fixed13), label17s, 16, 168);
  gtk_widget_set_size_request (label17s, 88, 24);

  sexes = gtk_label_new (_("Sexe:"));
  gtk_widget_show (sexes);
  gtk_fixed_put (GTK_FIXED (fixed13), sexes, 32, 216);
  gtk_widget_set_size_request (sexes, 49, 17);

  label19s = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label19s);
  gtk_fixed_put (GTK_FIXED (fixed13), label19s, 8, 264);
  gtk_widget_set_size_request (label19s, 144, 23);

  label20s = gtk_label_new (_("Num tel:"));
  gtk_widget_show (label20s);
  gtk_fixed_put (GTK_FIXED (fixed13), label20s, 24, 312);
  gtk_widget_set_size_request (label20s, 88, 24);

  label21s = gtk_label_new (_("Adresse:"));
  gtk_widget_show (label21s);
  gtk_fixed_put (GTK_FIXED (fixed13), label21s, 24, 360);
  gtk_widget_set_size_request (label21s, 88, 24);

  label18s = gtk_label_new (_("E-mail:"));
  gtk_widget_show (label18s);
  gtk_fixed_put (GTK_FIXED (fixed13), label18s, 32, 408);
  gtk_widget_set_size_request (label18s, 72, 24);

  label34s = gtk_label_new (_("Pass:"));
  gtk_widget_show (label34s);
  gtk_fixed_put (GTK_FIXED (fixed13), label34s, 32, 456);
  gtk_widget_set_size_request (label34s, 72, 24);

  combobox2s = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2s);
  gtk_fixed_put (GTK_FIXED (fixed13), combobox2s, 128, 216);
  gtk_widget_set_size_request (combobox2s, 160, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2s), _("FEMME"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2s), _("HOMME"));

  label36s = gtk_label_new ("");
  gtk_widget_show (label36s);
  gtk_fixed_put (GTK_FIXED (fixed13), label36s, 112, 504);
  gtk_widget_set_size_request (label36s, 192, 25);

  retour_Administrateur = gtk_button_new ();
  gtk_widget_show (retour_Administrateur);
  gtk_fixed_put (GTK_FIXED (fixed13), retour_Administrateur, 0, 544);
  gtk_widget_set_size_request (retour_Administrateur, 120, 37);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (retour_Administrateur), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label90 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label90);
  gtk_box_pack_start (GTK_BOX (hbox21), label90, FALSE, FALSE, 0);

  supprimer_agent = gtk_button_new ();
  gtk_widget_show (supprimer_agent);
  gtk_fixed_put (GTK_FIXED (fixed13), supprimer_agent, 136, 544);
  gtk_widget_set_size_request (supprimer_agent, 120, 37);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (supprimer_agent), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label91 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox22), label91, FALSE, FALSE, 0);

  confirmer_modif_agent = gtk_button_new ();
  gtk_widget_show (confirmer_modif_agent);
  gtk_fixed_put (GTK_FIXED (fixed13), confirmer_modif_agent, 272, 544);
  gtk_widget_set_size_request (confirmer_modif_agent, 120, 37);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (confirmer_modif_agent), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label92 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox23), label92, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) retour_Administrateur, "clicked",
                    G_CALLBACK (on_retour_Administrateur_clicked),
                    NULL);
  g_signal_connect ((gpointer) confirmer_modif_agent, "clicked",
                    G_CALLBACK (on_confirmer_modif_agent_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5s, window5s, "window5s");
  GLADE_HOOKUP_OBJECT (window5s, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (window5s, entry15s, "entry15s");
  GLADE_HOOKUP_OBJECT (window5s, entry16s, "entry16s");
  GLADE_HOOKUP_OBJECT (window5s, entry8s, "entry8s");
  GLADE_HOOKUP_OBJECT (window5s, entry9s, "entry9s");
  GLADE_HOOKUP_OBJECT (window5s, spinbutton4s, "spinbutton4s");
  GLADE_HOOKUP_OBJECT (window5s, spinbutton5s, "spinbutton5s");
  GLADE_HOOKUP_OBJECT (window5s, spinbutton6s, "spinbutton6s");
  GLADE_HOOKUP_OBJECT (window5s, entry11s, "entry11s");
  GLADE_HOOKUP_OBJECT (window5s, entry12s, "entry12s");
  GLADE_HOOKUP_OBJECT (window5s, entry10s, "entry10s");
  GLADE_HOOKUP_OBJECT (window5s, entry18s, "entry18s");
  GLADE_HOOKUP_OBJECT (window5s, labelid2s, "labelid2s");
  GLADE_HOOKUP_OBJECT (window5s, labelpassword2s, "labelpassword2s");
  GLADE_HOOKUP_OBJECT (window5s, label16s, "label16s");
  GLADE_HOOKUP_OBJECT (window5s, label17s, "label17s");
  GLADE_HOOKUP_OBJECT (window5s, sexes, "sexes");
  GLADE_HOOKUP_OBJECT (window5s, label19s, "label19s");
  GLADE_HOOKUP_OBJECT (window5s, label20s, "label20s");
  GLADE_HOOKUP_OBJECT (window5s, label21s, "label21s");
  GLADE_HOOKUP_OBJECT (window5s, label18s, "label18s");
  GLADE_HOOKUP_OBJECT (window5s, label34s, "label34s");
  GLADE_HOOKUP_OBJECT (window5s, combobox2s, "combobox2s");
  GLADE_HOOKUP_OBJECT (window5s, label36s, "label36s");
  GLADE_HOOKUP_OBJECT (window5s, retour_Administrateur, "retour_Administrateur");
  GLADE_HOOKUP_OBJECT (window5s, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window5s, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window5s, image21, "image21");
  GLADE_HOOKUP_OBJECT (window5s, label90, "label90");
  GLADE_HOOKUP_OBJECT (window5s, supprimer_agent, "supprimer_agent");
  GLADE_HOOKUP_OBJECT (window5s, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window5s, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window5s, image22, "image22");
  GLADE_HOOKUP_OBJECT (window5s, label91, "label91");
  GLADE_HOOKUP_OBJECT (window5s, confirmer_modif_agent, "confirmer_modif_agent");
  GLADE_HOOKUP_OBJECT (window5s, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window5s, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window5s, image23, "image23");
  GLADE_HOOKUP_OBJECT (window5s, label92, "label92");

  return window5s;
}

GtkWidget*
create_pagedacceil (void)
{
  GtkWidget *pagedacceil;
  GtkWidget *fixed14;
  GtkWidget *label93;
  GtkWidget *image24;
  GtkWidget *buttonlogin;
  GtkWidget *buttoncatalogue;
  GtkWidget *buttonquiter;
  GtkWidget *buttonsign_up;

  pagedacceil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (pagedacceil), _("Page d'acceil"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (pagedacceil), fixed14);

  label93 = gtk_label_new (_("<span \nforeground=\"blue\"><b>Sky travel</b></span>\n"));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed14), label93, 152, 32);
  gtk_widget_set_size_request (label93, 112, 56);
  gtk_label_set_use_markup (GTK_LABEL (label93), TRUE);

  image24 = create_pixmap (pagedacceil, NULL);
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed14), image24, 48, 8);
  gtk_widget_set_size_request (image24, 72, 80);

  buttonlogin = gtk_button_new_with_mnemonic (_("login"));
  gtk_widget_show (buttonlogin);
  gtk_fixed_put (GTK_FIXED (fixed14), buttonlogin, 56, 96);
  gtk_widget_set_size_request (buttonlogin, 127, 77);

  buttoncatalogue = gtk_button_new_with_mnemonic (_("Catalogue"));
  gtk_widget_show (buttoncatalogue);
  gtk_fixed_put (GTK_FIXED (fixed14), buttoncatalogue, 216, 96);
  gtk_widget_set_size_request (buttoncatalogue, 127, 77);

  buttonquiter = gtk_button_new_with_mnemonic (_("Quiter"));
  gtk_widget_show (buttonquiter);
  gtk_fixed_put (GTK_FIXED (fixed14), buttonquiter, 216, 184);
  gtk_widget_set_size_request (buttonquiter, 127, 77);

  buttonsign_up = gtk_button_new_with_mnemonic (_("sign up"));
  gtk_widget_show (buttonsign_up);
  gtk_fixed_put (GTK_FIXED (fixed14), buttonsign_up, 56, 184);
  gtk_widget_set_size_request (buttonsign_up, 127, 77);

  g_signal_connect ((gpointer) buttonlogin, "clicked",
                    G_CALLBACK (on_buttonlogin_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttoncatalogue, "clicked",
                    G_CALLBACK (on_buttoncatalogue_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonquiter, "clicked",
                    G_CALLBACK (on_buttonquiter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsign_up, "clicked",
                    G_CALLBACK (on_buttonsign_up_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (pagedacceil, pagedacceil, "pagedacceil");
  GLADE_HOOKUP_OBJECT (pagedacceil, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (pagedacceil, label93, "label93");
  GLADE_HOOKUP_OBJECT (pagedacceil, image24, "image24");
  GLADE_HOOKUP_OBJECT (pagedacceil, buttonlogin, "buttonlogin");
  GLADE_HOOKUP_OBJECT (pagedacceil, buttoncatalogue, "buttoncatalogue");
  GLADE_HOOKUP_OBJECT (pagedacceil, buttonquiter, "buttonquiter");
  GLADE_HOOKUP_OBJECT (pagedacceil, buttonsign_up, "buttonsign_up");

  return pagedacceil;
}

GtkWidget*
create_loginwindow (void)
{
  GtkWidget *loginwindow;
  GtkWidget *fixed15;
  GtkWidget *label94;
  GtkWidget *login;
  GtkWidget *password;
  GtkWidget *label95;
  GtkWidget *label96;
  GtkWidget *login_button;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image25;
  GtkWidget *label25;

  loginwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (loginwindow), _("sky travel"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (loginwindow), fixed15);

  label94 = gtk_label_new (_("Welcome to sky travel"));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed15), label94, 120, 24);
  gtk_widget_set_size_request (label94, 176, 25);

  login = gtk_entry_new ();
  gtk_widget_show (login);
  gtk_fixed_put (GTK_FIXED (fixed15), login, 144, 88);
  gtk_widget_set_size_request (login, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (login), 8226);

  password = gtk_entry_new ();
  gtk_widget_show (password);
  gtk_fixed_put (GTK_FIXED (fixed15), password, 144, 152);
  gtk_widget_set_size_request (password, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (password), 8226);

  label95 = gtk_label_new (_("Login:"));
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed15), label95, 56, 88);
  gtk_widget_set_size_request (label95, 64, 24);

  label96 = gtk_label_new (_("Password:"));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed15), label96, 40, 152);
  gtk_widget_set_size_request (label96, 80, 24);

  login_button = gtk_button_new ();
  gtk_widget_show (login_button);
  gtk_fixed_put (GTK_FIXED (fixed15), login_button, 144, 224);
  gtk_widget_set_size_request (login_button, 128, 29);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (login_button), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image25 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox24), image25, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Connect"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox24), label25, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) login_button, "clicked",
                    G_CALLBACK (on_login_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (loginwindow, loginwindow, "loginwindow");
  GLADE_HOOKUP_OBJECT (loginwindow, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (loginwindow, label94, "label94");
  GLADE_HOOKUP_OBJECT (loginwindow, login, "login");
  GLADE_HOOKUP_OBJECT (loginwindow, password, "password");
  GLADE_HOOKUP_OBJECT (loginwindow, label95, "label95");
  GLADE_HOOKUP_OBJECT (loginwindow, label96, "label96");
  GLADE_HOOKUP_OBJECT (loginwindow, login_button, "login_button");
  GLADE_HOOKUP_OBJECT (loginwindow, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (loginwindow, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (loginwindow, image25, "image25");
  GLADE_HOOKUP_OBJECT (loginwindow, label25, "label25");

  return loginwindow;
}

GtkWidget*
create_espace_client (void)
{
  GtkWidget *espace_client;
  GtkWidget *fixed16;
  GtkWidget *notebook1m;
  GtkWidget *empty_notebook_page;
  GtkWidget *label97;
  GtkWidget *label98;
  GtkWidget *label99;
  GtkWidget *fixed17;
  GtkWidget *treeview2m;
  GtkWidget *label29m;
  GtkWidget *nomc;
  GtkWidget *prenomc;
  GtkWidget *cinc;
  GtkWidget *messagec;
  GtkWidget *affich;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image27;
  GtkWidget *label106;
  GtkWidget *modif;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image28;
  GtkWidget *label107;
  GtkWidget *supp;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image29;
  GtkWidget *label108;
  GtkWidget *envoyerm;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image26;
  GtkWidget *label105;
  GtkWidget *label32m;
  GtkWidget *label31m;
  GtkWidget *label30m;
  GtkWidget *avis;

  espace_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace_client), _("Espace Client"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (espace_client), fixed16);

  notebook1m = gtk_notebook_new ();
  gtk_widget_show (notebook1m);
  gtk_fixed_put (GTK_FIXED (fixed16), notebook1m, 0, 0);
  gtk_widget_set_size_request (notebook1m, 768, 504);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1m), empty_notebook_page);

  label97 = gtk_label_new (_("label97"));
  gtk_widget_show (label97);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1m), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1m), 0), label97);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1m), empty_notebook_page);

  label98 = gtk_label_new (_("label98"));
  gtk_widget_show (label98);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1m), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1m), 1), label98);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1m), empty_notebook_page);

  label99 = gtk_label_new (_("label99"));
  gtk_widget_show (label99);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1m), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1m), 2), label99);

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (notebook1m), fixed17);

  treeview2m = gtk_tree_view_new ();
  gtk_widget_show (treeview2m);
  gtk_fixed_put (GTK_FIXED (fixed17), treeview2m, 352, 56);
  gtk_widget_set_size_request (treeview2m, 408, 416);

  label29m = gtk_label_new (_("Nom:"));
  gtk_widget_show (label29m);
  gtk_fixed_put (GTK_FIXED (fixed17), label29m, 0, 48);
  gtk_widget_set_size_request (label29m, 80, 32);

  nomc = gtk_entry_new ();
  gtk_widget_show (nomc);
  gtk_fixed_put (GTK_FIXED (fixed17), nomc, 88, 48);
  gtk_widget_set_size_request (nomc, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomc), 8226);

  prenomc = gtk_entry_new ();
  gtk_widget_show (prenomc);
  gtk_fixed_put (GTK_FIXED (fixed17), prenomc, 88, 128);
  gtk_widget_set_size_request (prenomc, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenomc), 8226);

  cinc = gtk_entry_new ();
  gtk_widget_show (cinc);
  gtk_fixed_put (GTK_FIXED (fixed17), cinc, 88, 200);
  gtk_widget_set_size_request (cinc, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinc), 8226);

  messagec = gtk_entry_new ();
  gtk_widget_show (messagec);
  gtk_fixed_put (GTK_FIXED (fixed17), messagec, 80, 272);
  gtk_widget_set_size_request (messagec, 256, 112);
  gtk_entry_set_invisible_char (GTK_ENTRY (messagec), 8226);

  affich = gtk_button_new ();
  gtk_widget_show (affich);
  gtk_fixed_put (GTK_FIXED (fixed17), affich, 352, 8);
  gtk_widget_set_size_request (affich, 104, 32);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (affich), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image27 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox26), image27, FALSE, FALSE, 0);

  label106 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label106);
  gtk_box_pack_start (GTK_BOX (hbox26), label106, FALSE, FALSE, 0);

  modif = gtk_button_new ();
  gtk_widget_show (modif);
  gtk_fixed_put (GTK_FIXED (fixed17), modif, 496, 8);
  gtk_widget_set_size_request (modif, 104, 32);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (modif), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image28 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox27), image28, FALSE, FALSE, 0);

  label107 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label107);
  gtk_box_pack_start (GTK_BOX (hbox27), label107, FALSE, FALSE, 0);

  supp = gtk_button_new ();
  gtk_widget_show (supp);
  gtk_fixed_put (GTK_FIXED (fixed17), supp, 640, 8);
  gtk_widget_set_size_request (supp, 112, 32);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (supp), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image29 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox28), image29, FALSE, FALSE, 0);

  label108 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label108);
  gtk_box_pack_start (GTK_BOX (hbox28), label108, FALSE, FALSE, 0);

  envoyerm = gtk_button_new ();
  gtk_widget_show (envoyerm);
  gtk_fixed_put (GTK_FIXED (fixed17), envoyerm, 216, 416);
  gtk_widget_set_size_request (envoyerm, 120, 40);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (envoyerm), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image26 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox25), image26, FALSE, FALSE, 0);

  label105 = gtk_label_new_with_mnemonic (_("Envoyer"));
  gtk_widget_show (label105);
  gtk_box_pack_start (GTK_BOX (hbox25), label105, FALSE, FALSE, 0);

  label32m = gtk_label_new (_("Message:"));
  gtk_widget_show (label32m);
  gtk_fixed_put (GTK_FIXED (fixed17), label32m, 0, 272);
  gtk_widget_set_size_request (label32m, 88, 32);

  label31m = gtk_label_new (_("Cin:"));
  gtk_widget_show (label31m);
  gtk_fixed_put (GTK_FIXED (fixed17), label31m, 0, 200);
  gtk_widget_set_size_request (label31m, 80, 32);

  label30m = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (label30m);
  gtk_fixed_put (GTK_FIXED (fixed17), label30m, 0, 128);
  gtk_widget_set_size_request (label30m, 80, 32);

  avis = gtk_label_new (_("Avis"));
  gtk_widget_show (avis);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1m), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1m), 3), avis);

  g_signal_connect ((gpointer) affich, "clicked",
                    G_CALLBACK (on_affich_clicked),
                    NULL);
  g_signal_connect ((gpointer) modif, "clicked",
                    G_CALLBACK (on_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) supp, "clicked",
                    G_CALLBACK (on_supp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_client, espace_client, "espace_client");
  GLADE_HOOKUP_OBJECT (espace_client, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (espace_client, notebook1m, "notebook1m");
  GLADE_HOOKUP_OBJECT (espace_client, label97, "label97");
  GLADE_HOOKUP_OBJECT (espace_client, label98, "label98");
  GLADE_HOOKUP_OBJECT (espace_client, label99, "label99");
  GLADE_HOOKUP_OBJECT (espace_client, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (espace_client, treeview2m, "treeview2m");
  GLADE_HOOKUP_OBJECT (espace_client, label29m, "label29m");
  GLADE_HOOKUP_OBJECT (espace_client, nomc, "nomc");
  GLADE_HOOKUP_OBJECT (espace_client, prenomc, "prenomc");
  GLADE_HOOKUP_OBJECT (espace_client, cinc, "cinc");
  GLADE_HOOKUP_OBJECT (espace_client, messagec, "messagec");
  GLADE_HOOKUP_OBJECT (espace_client, affich, "affich");
  GLADE_HOOKUP_OBJECT (espace_client, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (espace_client, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (espace_client, image27, "image27");
  GLADE_HOOKUP_OBJECT (espace_client, label106, "label106");
  GLADE_HOOKUP_OBJECT (espace_client, modif, "modif");
  GLADE_HOOKUP_OBJECT (espace_client, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (espace_client, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (espace_client, image28, "image28");
  GLADE_HOOKUP_OBJECT (espace_client, label107, "label107");
  GLADE_HOOKUP_OBJECT (espace_client, supp, "supp");
  GLADE_HOOKUP_OBJECT (espace_client, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (espace_client, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (espace_client, image29, "image29");
  GLADE_HOOKUP_OBJECT (espace_client, label108, "label108");
  GLADE_HOOKUP_OBJECT (espace_client, envoyerm, "envoyerm");
  GLADE_HOOKUP_OBJECT (espace_client, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (espace_client, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (espace_client, image26, "image26");
  GLADE_HOOKUP_OBJECT (espace_client, label105, "label105");
  GLADE_HOOKUP_OBJECT (espace_client, label32m, "label32m");
  GLADE_HOOKUP_OBJECT (espace_client, label31m, "label31m");
  GLADE_HOOKUP_OBJECT (espace_client, label30m, "label30m");
  GLADE_HOOKUP_OBJECT (espace_client, avis, "avis");

  return espace_client;
}

GtkWidget*
create_window2m (void)
{
  GtkWidget *window2m;
  GtkWidget *fixed18;
  GtkWidget *entry3m;
  GtkWidget *label37m;
  GtkWidget *validerm;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image30;
  GtkWidget *label110;

  window2m = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2m), _("Supprimer"));

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (window2m), fixed18);

  entry3m = gtk_entry_new ();
  gtk_widget_show (entry3m);
  gtk_fixed_put (GTK_FIXED (fixed18), entry3m, 128, 64);
  gtk_widget_set_size_request (entry3m, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3m), 8226);

  label37m = gtk_label_new (_("Cin:"));
  gtk_widget_show (label37m);
  gtk_fixed_put (GTK_FIXED (fixed18), label37m, 40, 56);
  gtk_widget_set_size_request (label37m, 88, 48);

  validerm = gtk_button_new ();
  gtk_widget_show (validerm);
  gtk_fixed_put (GTK_FIXED (fixed18), validerm, 144, 152);
  gtk_widget_set_size_request (validerm, 120, 40);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (validerm), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image30 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox29), image30, FALSE, FALSE, 0);

  label110 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label110);
  gtk_box_pack_start (GTK_BOX (hbox29), label110, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) validerm, "clicked",
                    G_CALLBACK (on_validerm_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2m, window2m, "window2m");
  GLADE_HOOKUP_OBJECT (window2m, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (window2m, entry3m, "entry3m");
  GLADE_HOOKUP_OBJECT (window2m, label37m, "label37m");
  GLADE_HOOKUP_OBJECT (window2m, validerm, "validerm");
  GLADE_HOOKUP_OBJECT (window2m, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (window2m, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (window2m, image30, "image30");
  GLADE_HOOKUP_OBJECT (window2m, label110, "label110");

  return window2m;
}

GtkWidget*
create_window3m (void)
{
  GtkWidget *window3m;
  GtkWidget *fixed19;
  GtkWidget *entry4m;
  GtkWidget *entry5m;
  GtkWidget *label38m;
  GtkWidget *modifierm;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image31;
  GtkWidget *label113;
  GtkWidget *label39m;

  window3m = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3m), _("Modifier"));

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (window3m), fixed19);

  entry4m = gtk_entry_new ();
  gtk_widget_show (entry4m);
  gtk_fixed_put (GTK_FIXED (fixed19), entry4m, 152, 40);
  gtk_widget_set_size_request (entry4m, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4m), 8226);

  entry5m = gtk_entry_new ();
  gtk_widget_show (entry5m);
  gtk_fixed_put (GTK_FIXED (fixed19), entry5m, 152, 96);
  gtk_widget_set_size_request (entry5m, 240, 112);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5m), 8226);

  label38m = gtk_label_new (_("Cin:"));
  gtk_widget_show (label38m);
  gtk_fixed_put (GTK_FIXED (fixed19), label38m, 64, 40);
  gtk_widget_set_size_request (label38m, 72, 32);

  modifierm = gtk_button_new ();
  gtk_widget_show (modifierm);
  gtk_fixed_put (GTK_FIXED (fixed19), modifierm, 144, 240);
  gtk_widget_set_size_request (modifierm, 112, 40);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (modifierm), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image31 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox30), image31, FALSE, FALSE, 0);

  label113 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label113);
  gtk_box_pack_start (GTK_BOX (hbox30), label113, FALSE, FALSE, 0);

  label39m = gtk_label_new (_("Nouveau avis:"));
  gtk_widget_show (label39m);
  gtk_fixed_put (GTK_FIXED (fixed19), label39m, 0, 80);
  gtk_widget_set_size_request (label39m, 160, 48);

  g_signal_connect ((gpointer) modifierm, "clicked",
                    G_CALLBACK (on_modifierm_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3m, window3m, "window3m");
  GLADE_HOOKUP_OBJECT (window3m, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (window3m, entry4m, "entry4m");
  GLADE_HOOKUP_OBJECT (window3m, entry5m, "entry5m");
  GLADE_HOOKUP_OBJECT (window3m, label38m, "label38m");
  GLADE_HOOKUP_OBJECT (window3m, modifierm, "modifierm");
  GLADE_HOOKUP_OBJECT (window3m, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (window3m, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (window3m, image31, "image31");
  GLADE_HOOKUP_OBJECT (window3m, label113, "label113");
  GLADE_HOOKUP_OBJECT (window3m, label39m, "label39m");

  return window3m;
}

