/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_ajouhotel (void);
GtkWidget* create_modifhotel (void);
GtkWidget* create_ajouvol (void);
GtkWidget* create_modifvol (void);
GtkWidget* create_window3s (void);
GtkWidget* create_window4s (void);
GtkWidget* create_window5s (void);
GtkWidget* create_pagedacceil (void);
GtkWidget* create_loginwindow (void);
GtkWidget* create_espace_client (void);
GtkWidget* create_window2m (void);
GtkWidget* create_window3m (void);
